20tab/UnrealEnginePython

- Source/UnrealEnginePython/Private/UnrealEnginePython.cpp
- Source/UnrealEnginePython/Public/PyCommandlet.cpp
- Source/UnrealEnginePython/Public/PyCommandlet.h
This pull request adds a basic python commandlet which can be invoked to execute a python script using a headless Unreal Engine instance.
It can be invoked by:
UE4Editor.exe -run=UnrealEnginePython.PyCommandlet <PATH_TO_PYTHON_SCRIPT> <PYTHON_SCRIPT_CMD_ARGS>
Example:
UE4Editor.exe -run=UnrealEnginePython.PyCommandlet C:\test_script.py --test_arg_a 1 2 3 4 -test_arg_b "Spaces In Args Will Work" -test_arg_c EscapedQuotes\"AlsoWork -test_arg_d "OtherEscapedCharacters\nAlsoWork"
The python script path is the only token expected and it is expected to come after any Unreal arguments. Any arguments desired to be available to python must come after the python script path. Unreal switches and parameters should work fine as long as they come before the python path.
The arguments format doesn't …
> Adds A Basic Python Commandlet.

- Source/UnrealEnginePython/Private/UEPyFARFilter.cpp
- Source/UnrealEnginePython/Public/PyCommandlet.cpp
The plugin was throwing compile errors on mac, so I made a few changes to resolve this.
- Fixed a few string literals missing cast in function args of UEPyFARFilter.
- Changed docstring argument for PyGetSetDef to char * (was erroneously bool).
- wcscpy_s was used in PyCommandlet but is not available on macOS as far as I know. I changed it to wcsncpy--which I think should be okay (?)
> Fixes for macOS build

- Source/UnrealEnginePython/Private/UEPyAssetUserData.cpp
Previously the data returned was not entirely accurate (relative_file was not actually relative) plus
this change is more future proof in cases where assets were imported from more than one file.
This change also adds extra metadata: timestamp and filehash.
> Refactors get_asset_import_data to return list of dicts.

- Source/UnrealEnginePython/Private/UnrealEnginePython.cpp
- Source/UnrealEnginePython/Private/UnrealEnginePythonPrivatePCH.h
Without this we get errors about PyGilState_Check already having a body.
> Fixes pygilstate compiler errors for Python < 3.

- Source/UnrealEnginePython/Private/UEPyEditor.cpp
- Source/UnrealEnginePython/Private/UEPyEngine.cpp
- Source/UnrealEnginePython/Private/UEPyFAssetData.cpp
- Source/UnrealEnginePython/Private/UEPyFAssetData.h
- Source/UnrealEnginePython/Private/UEPyModule.cpp
- Source/UnrealEnginePython/Private/UnrealEnginePythonPrivatePCH.h
This pull request adds a basic FAssetData wrapper and the ability to get FAssetData objects rather than fully loading assets when calling get_asset_by_filter. 
Before merging I had a few questions. Should we use keyword args for this and add this functionality to the other get_asset* functions? Keyword args haven't been used anywhere else so I did not look into using them here yet.
This is an important addition as the cost of fully loading assets is much higher than simply getting back the FAssetData objects.
> Add flag to return FAssetData

- README.md
I updated the README to discuss get_py_proxy as mentioned in issue #104.
> Updated README to discuss get_py_proxy

- Source/UnrealEnginePython/Private/UEPyFARFilter.cpp
Resolves a bug which can cause crashes due to dealloc being called on a ue_PyFarFilter object when the new method has never been called.
> Fixes issue with PyFARFilter not initializing correctly.

- Source/UnrealEnginePython/Private/UEPyAudio.cpp
- Source/UnrealEnginePython/Private/UEPyAudio.h
- Source/UnrealEnginePython/Private/UEPyModule.cpp
This function accepts a USoundWaveProcedural and a Python buffer object. The 'QueueAudio' function on the USoundWaveProcedural is called, passing along the binary data within the buffer. This audio can then be played via normal Unreal methods (adding to an AudioComponent, playing sound at a location, etc.).
I'm not entirely sure if this fits in with the rest of the project, given it's a function that applies just for one class (USoundWaveProcedural). Even so, I don't think there is a way to do it entirely within Python, since you'd need to pass in a raw uint8* array to the function.
> Created a 'write_audio_to_buffer' function.

- Source/UnrealEnginePython/Private/Http/UEPyIHttpRequest.h
- Source/UnrealEnginePython/Private/Http/UEPyIHttpResponse.h
- Source/UnrealEnginePython/Private/Slate/UEPyFSlateIcon.cpp
- Source/UnrealEnginePython/Private/Slate/UEPyFToolBarBuilder.cpp
-Adding missing extern storage specifier
-Default initializing FSlateIcon params so instantiating FSlateIcon() in python doesn't crash
> Enabling FToolBarBuilder to be manually instantiated

- Source/UnrealEnginePython/Private/UEPyEngine.h
- Source/UnrealEnginePython/Private/UEPyModule.cpp
- Source/UnrealEnginePython/Private/UEPyWorld.cpp
- Source/UnrealEnginePython/Private/UEPyWorld.h
- Source/UnrealEnginePython/Public/PythonBlueprintFunctionLibrary.h
Adding ability to find object based on specific world (useful for PIE).
Syntax is world.find_object('MyLevelName:PersistentLevel.BP_ActorName')
> Missing include header + ability to find_object scoped to current game world

- Source/PythonEditor/Private/PythonProjectEditor.cpp
- Fix for a crash during UE4 editor shutdown when python editor was opened before
> UE4 Editor shutdown crash fix

- examples/get_uobjects_in_loaded_levels.py
Tested it in a production scene and some times, streaming_level.LoadedLevel was returning None causing a crash erroring
> streaming_level.LoadedLevel returned None

- Source/UnrealEnginePython/Private/UObject/UEPyLandscape.cpp
Very simple fix. On my dev environment, certain warnings get promoted to errors and the overflow here is one of them. 
The print formatter assumes int, but the result can obviously be much wider.
Fixes #249.
> Fix debug print type overflow

- Source/UnrealEnginePython/Public/PythonHouseKeeper.h
This fixes this issue:
https://github.com/20tab/UnrealEnginePython/issues/329
Basically, the log is logging an error while it should just be an info message.
> Fixed logging message for garbage collect delegates.

- Source/UnrealEnginePython/Private/Wrappers/UEPyFRandomStream.cpp
This caused a compilation error when packaging my project with UE-4.19
> fixed typo in UEPyFRandomStream.cpp

- Source/UnrealEnginePython/Private/UEPyModule.cpp
This is to fix up a snag I hit when working with a `K2Node_CallFunction`.
I was attempting to run the following code, which I felt should work. This was to call a function on another blueprint.
callFuncNode = K2Node_CallFunction()
callFuncNode.FunctionReference = MemberReference( MemberName="MyFunction", MemberParent=otherBP.GeneratedClass )
This failed with an error saying `invalid value for UProperty`.
This is because MemberReference.MemberParent is of type UObject, rather than UClass, as it can take various types of object, one of which is a UClass (as in this case)
What this PR does is allow a UClass to be assigned to a UObjectPropertyBase property as well as the existing property types.
> Allow Class objects to be assigned to Properties that take a UObject

- README.md
The previous README.md listed a non-existent .h file to modify to enable threading. This PR replaces it with the correct one.
> Fix the name of the .h file to modify to enable threading

- tools/generate_pyi_stubs.py
Hey @rdeioris, I've made a script to create pyi stubs for `unreal_engine` as you suggested in #384. It will generate this directory structure:
```
unreal_engine/__init__.pyi
```
Tweaked example from readme seems to work fine in PyCharm:
```python
import unreal_engine as ue
ue.log('Hello i am a Python module')
class Hero:
uobject: ue.UObject
def begin_play(self):
ue.log('Begin Play on Hero class')
def tick(self, delta_time):
location = self.uobject.get_actor_location()
location.z += 100 * delta_time
self.uobject.set_actor_location(location)
```
This closes #384, closes #221.
> Script to generate pyi stubs.

- examples/sequencer_scripting.py
I've modified the sequencer example based on changes to how a Camera is assigned to a CameraCutSection
> Fix sequencer example based on change since 4.18

- Source/UnrealEnginePython/Private/UEPyModule.cpp
- Source/UnrealEnginePython/Private/Wrappers/UEPyFColor.cpp
- Source/UnrealEnginePython/Private/Wrappers/UEPyFColor.h
- Source/UnrealEnginePython/Private/Wrappers/UEPyFLinearColor.cpp
- Source/UnrealEnginePython/Private/Wrappers/UEPyFLinearColor.h
- Source/UnrealEnginePython/Private/Wrappers/UEPyFQuat.cpp
- Source/UnrealEnginePython/Private/Wrappers/UEPyFQuat.h
- Source/UnrealEnginePython/Private/Wrappers/UEPyFRotator.cpp
- Source/UnrealEnginePython/Private/Wrappers/UEPyFRotator.h
- Source/UnrealEnginePython/Private/Wrappers/UEPyFTransform.cpp
- Source/UnrealEnginePython/Private/Wrappers/UEPyFTransform.h
- Source/UnrealEnginePython/Private/Wrappers/UEPyFVector.cpp
- Source/UnrealEnginePython/Private/Wrappers/UEPyFVector.h
Given a C++ parent class like:
```
UCLASS()
class UPYDEV_API ACActor : public AActor
{
...
UFUNCTION(BlueprintCallable, BlueprintImplementableEvent)
void ReceiveAVector(FVector newVector);
...
```
this patch makes it possible to have a Python subclass like:
```
import unreal_engine as ue
from unreal_engine.classes import CActor
from unreal_engine import FVector, FRotator, FLinearColor, FQuat, FColor, FTransform
class PActor(CActor):
def ReceiveAVector(self, newVector : FVector):
```
Added support for FVector, FRotator, FLinearColor, FColor, FTransform, and FQuat.
> add support for native types like FVector in method params

- Source/UnrealEnginePython/Private/UEPyModule.cpp
- Source/UnrealEnginePython/Private/UObject/UEPyStaticMesh.cpp
- Source/UnrealEnginePython/Private/UObject/UEPyStaticMesh.h
This patch makes it so you can get the BoxSphereBounds from a UStaticMesh object:
```py
from unreal_engine.classes import StaticMesh
sm = unreal_engine.load_object(StaticMesh, '/Game/Meshes/...')
b = sm.get_static_mesh_bounds()
print(b.BoxExtent, b.SphereRadius)
```
> added get_static_mesh_bounds method

- Source/UnrealEnginePython/Private/PyCommandlet.cpp
- Source/UnrealEnginePython/Private/UnrealEnginePython.cpp
This pr is a fix for issue #602 
Please let me know if there is anything else it should include.  Thanks to @ishyesh for figuring out the solution.
> Added TCHAR_TO_WCHAR to fix issue 602

- Source/UnrealEnginePython/Private/Wrappers/UEPyFVector.cpp
While working on support for FVector2D I noticed what seems to be a minor bug with FVector. Currently if you try to do this:
```py
from unreal_engine import FVector
v = FVector(10, 15, 18)
print(v/3)
```
you get this error:
```py
TypeError: unsupported operand type(s) for /: 'unreal_engine.FVector' and 'int'
```
With the patch you get what you'd expect:
```py
<unreal_engine.FVector {'x': 3.3333334922790527, 'y': 5.0, 'z': 6.0}>
```
> Fixed division bug in FVector

- Source/UnrealEnginePython/Private/UnrealEnginePython.cpp
Thanks for accepting the previous PR. I’m sorry I missed these compilation warnings, here’s a PR to fix them.
[ WARNING ] 2>Engine\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UnrealEnginePython.cpp(455): warning C4996: 'fileno': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _fileno. See online help for details.
[  NOTIF  ] 2>  C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h(2459): note: see declaration of 'fileno'
[ WARNING ] 2>Engine\Plugins\UnrealEnginePython\Source\UnrealEnginePython\Private\UnrealEnginePython.cpp(456): warning C4996: 'fileno': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _fileno. See online help for details.
[  NOTIF  ] 2>  C:\Program …
> Use C++ conformant “_fileno” instead of “fileno”.

- Source/UnrealEnginePython/Private/PyCommandlet.cpp
- Source/UnrealEnginePython/Private/UnrealEnginePython.cpp
This is a fix for issue #602 that includes a version check so that pre 4.20 projects aren't affected.
If this check is not necessary with @samhocevar pull request #627 please let me know and I will delete this.
> Adds version checking before calling TCHAR_TO_WCHAR

- Source/UnrealEnginePython/UnrealEnginePython.Build.cs
A minor quality-of-life patch for your consideration: have build.cs check an env var specific to UnrealEnginePython for where to locate the Python to use.
Background: we use different versions of Python for different things, and on Windows for various reasons we end up having to put them in non-standard locations, and unfortunately also sometimes have to have multiple versions of Python installed on a single machine. So every time we clone UEP we have to go in and customize where it looks, but if we could just set an env var then we wouldn't need to change UEP to do that. But we can't change e.g. PYTHONHOME because we can't mess up anything else that uses Python, and we want to make sure that we all use the exact same version of Python with UEP.
I have zero preference for what the env var …
> look for python in alternate custom location

- Source/UnrealEnginePython/Private/UEPyModule.h
This macro was only introduced in UE4.20. We copy it if wchar_t and TCHAR differ in size.
> Add backwards compatibility macro for TCHAR_TO_WCHAR.

- Source/UnrealEnginePython/Private/PythonDelegate.cpp
- Source/UnrealEnginePython/Private/UEPyModule.cpp
- Source/UnrealEnginePython/Private/UEPyModule.h
- Source/UnrealEnginePython/Private/UObject/UEPyObject.cpp
- Source/UnrealEnginePython/Private/UObject/UEPyObject.h
- Source/UnrealEnginePython/Public/PythonDelegate.h
- Source/UnrealEnginePython/Public/PythonHouseKeeper.h
Currently you can bind a Python callable to an event dispatcher:
```py
someEventEmitter.bind_event('SomeEvent', self.OnSomeEvent)
```
But I couldn't find any way to later unbind that. This patch adds support for:
```py
someEventEmitter.unbind_event('SomeEvent', self.OnSomeEvent)
```
> Add support for unbind_event

- Source/UnrealEnginePython/Private/Blueprint/UEPyEdGraphPin.cpp
> Add break_all_links() and get_linked_to()

- Source/UnrealEnginePython/UnrealEnginePython.Build.cs
Commit 30e723241336db7241f4215d50773803161ce6f3 seems to have broken the build in older versions of UE4 (I'm using 4.19 and it's broken there at least).
The change that broke it was the removal of "UnrealEnginePython/Private" from the PrivateIncludePaths in the build.cs file.
This commit adds it back in for older versions of UE4, using the UE_4_XX_OR_LATER macro they started [introducing in 4.17](https://docs.unrealengine.com/en-us/Support/Builds/ReleaseNotes/4_17#programming).
> fixed 4.19 build

- Source/UnrealEnginePython/Private/PythonHouseKeeper.cpp
- Source/UnrealEnginePython/Public/PythonHouseKeeper.h
- Source/UnrealEnginePython/UnrealEnginePython.Build.cs
Currently PythonHouseKeeper is implemented entirely in a header file, which makes it cumbersome to work with because the smallest modification causes pretty much the entire project to be rebuilt (e.g. I was debugging something and just wanted to add a log message temporarily - each tweak meant a full rebuild).
This is a QOL change that doesn't change any functionality at all; it merely splits the implementation into a .cpp file.
> Split PythonHouseKeeper

- Source/UnrealEnginePython/Private/Blueprint/UEPyEdGraph.cpp
- Source/UnrealEnginePython/Private/Blueprint/UEPyEdGraph.h
- Source/UnrealEnginePython/Private/UEPyModule.cpp
Adding 2 functions for increased EdGraph/AnimGraph functionality.  The ability to reconstruct a node to show recently set asPin fields to True, and to delete a node from a graph.
> Adding edgraph functions reconstruct_node() and remove_node()
