Source/UnrealEnginePython/Private/UEPyEditor.cpp
Source/UnrealEnginePython/Private/UEPyFARFilter.cpp
Source/UnrealEnginePython/Private/UEPyFARFilter.h
Source/UnrealEnginePython/Private/UEPyModule.cpp
Source/UnrealEnginePython/Private/UnrealEnginePythonPrivatePCH.h

Addresses #41.
Please take a look and let me know if you'd like me to change anything. The functionality is present but I'm not 100% sure it's coded in the best way.
Perhaps line 289 shouldn't be hardcoded and an optional kwarg should be added.

Adds FARfilter support

---

Source/UnrealEnginePython/Private/UEPyActor.cpp
Source/UnrealEnginePython/Private/UEPyAudio.cpp
Source/UnrealEnginePython/Private/UEPyEditor.cpp
Source/UnrealEnginePython/Private/UEPyEnumsImporter.cpp
Source/UnrealEnginePython/Private/UEPyModule.cpp
Source/UnrealEnginePython/Private/UEPyObject.cpp
Source/UnrealEnginePython/Private/UEPyUClassesImporter.cpp
Source/UnrealEnginePython/Private/UnrealEnginePython.cpp
Source/UnrealEnginePython/Private/UnrealEnginePythonPrivatePCH.h

Addresses #44 and will check for PyString in addition to PyUnicode when running python 2.7.

Adds in check for PyString when running python27

---

Source/UnrealEnginePython/Private/UEPyAssetUserData.cpp
Source/UnrealEnginePython/Private/UEPyAssetUserData.h
Source/UnrealEnginePython/Private/UEPyModule.cpp
Source/UnrealEnginePython/Private/UEPyObject.cpp
Source/UnrealEnginePython/Private/UEPyObject.h
Source/UnrealEnginePython/Private/UEPyPackage.cpp
Source/UnrealEnginePython/Private/UEPyPackage.h

Adds methods asset_import_data, asset_can_reimport, package_get_filename, package_is_dirty.
Makes name optional for save_package if UObject is a UPackage.
These are all bundled together because I was working on them all at once. Let me know if you'd prefer I break them up or if you'd like me to adjust anything. I won't be able to work on anything for the next few days but will pick up where I left off next week.

Adds new methods.

---

Source/UnrealEnginePython/Private/UEPyModule.cpp
Source/UnrealEnginePython/Private/UEPyPhysics.cpp
Source/UnrealEnginePython/Private/UEPyPhysics.h

add function:
- get_physics_linear_velocity
- set_physics_linear_velocity
fix function:
- sett_physics_angular_velocity

added and fixed functions

---

Source/UnrealEnginePython/Private/UEPyObject.cpp

Also fixes a small issue in asset_reimport.

Allows a package to also call save_package.

---

Source/UnrealEnginePython/Private/UEPyEditor.cpp
Source/UnrealEnginePython/Public/PyCommandlet.cpp

Fix a couple of errors with Mac compilation:
* Strings not being cast correctly
* With python 2.7, use of Windows-specific strcpy_s function

Fix Mac compilation

---

Source/UnrealEnginePython/Private/UnrealEnginePython.cpp

move the thread state and global_dict block up to enable it compiles in python 2.7 as well

Fixed the build on linux python2.7

---

README.md

Unreal Engine crashes whenever a QApplication gets created twice

fixed #129 engine crash

---

Source/UnrealEnginePython/Private/Fbx/UEPyFbxIOSettings.cpp
Source/UnrealEnginePython/Private/Fbx/UEPyFbxImporter.cpp
Source/UnrealEnginePython/Private/Fbx/UEPyFbxManager.cpp
Source/UnrealEnginePython/Private/Fbx/UEPyFbxNode.cpp
Source/UnrealEnginePython/Private/Fbx/UEPyFbxObject.cpp
Source/UnrealEnginePython/Private/Fbx/UEPyFbxProperty.cpp
Source/UnrealEnginePython/Private/Fbx/UEPyFbxScene.cpp

Fixes the issue:
#183 
Details:
The header file name for Fbx has been changed but it was not changed in the header include codes.

Changed the include lines to handle new file names

---

Source/UnrealEnginePython/Private/PythonComponent.cpp
Source/UnrealEnginePython/Public/PythonComponent.h

Hi. I would like to add new useful function to main code of plugin.

PythonComponent: Added function to return MAP strings.

---

Source/UnrealEnginePython/Private/PythonComponent.cpp
Source/UnrealEnginePython/Public/PythonComponent.h

I have added end_play to clean python resources. It might be useful in case when you need for example close connection or save data properly after exit game.

Added end_play to cleanup python resources correctly.

---

UnrealEnginePython.uplugin

not sure why it changed every line... sometimes that happens when I use vim in git bash but I don't recall doing that... anyway, added plugin dependency to meet new 4.17 requirement that caused a warning during compile.

Added LevelSequenceEditor as Plugin dependency per new 4.17 requirements

---

Source/UnrealEnginePython/Private/UEPyEditor.cpp

Fixed a compilation error in UE-4.17

---

docs/Collections_API.md

Added the remaining functions.

Added the rest of the documentation

---

Source/UnrealEnginePython/Private/CollectionManager/UEPyICollectionManager.cpp

Renamed create_unique_connection_name to create_unique_collection_name

Typo in create_unique_connection_name

---

docs/Transactions_API.md

Related to: https://github.com/20tab/UnrealEnginePython/issues/298

Adding documentation for transactions with attribute/property modifications

---

docs/Material_API.md

Documented the additional parameters for the create_material_instance function.

Added extra info on create_material_instance

---

Source/UnrealEnginePython/Private/Fbx/UEPyFbxObject.cpp

left/right tangents, tangent mode and interpolation mode

Add new geters for fbx curve key

---

Source/PythonEditor/Private/PythonProject.cpp
Source/UnrealEnginePython/Private/UnrealEnginePython.cpp
Source/UnrealEnginePython/Public/UnrealEnginePython.h

This PR adds python search paths as per #398.

Add additional search paths for python modules

---

Source/UnrealEnginePython/Private/UEPyModule.cpp
Source/UnrealEnginePython/Private/Wrappers/UEPyFSlowTask.cpp
Source/UnrealEnginePython/Private/Wrappers/UEPyFSlowTask.h
examples/slow_task.py

This PR adds support for FSlowTask, allowing for progress bars to be created inside the editor when a slow task is being performed.
This PR also includes an example for how to use it.

FSlowTask support

---

Source/UnrealEnginePython/Private/UEPyEditor.cpp

have the same behaviour than context menu rename in content browser:
checkout redirector, mark for add newly created renamed asset.
python code sample:
_filter = FARFilter()
_filter.class_names = ['Texture2D']
textures = ue.get_assets_by_filter(_filter)
for texture in textures:
name = texture.get_name()			
index = name.rfind('_BC') 
if index > -1 : 
pathName = texture.get_path_name()
newname = name[0 : index] + '_basecolor'
ue.rename_asset(pathName, newname)

fix rename asset definition

---

Source/UnrealEnginePython/Private/PythonFunction.cpp

In 4.19 and above, the NativeFunction interface adds a Context parameter
that contains the UObject instance this function is being called on.
CallPythonCallable uses this instead of Stack.Object when the engine is
newer.

Fix PythonFunction for 4.19

---

Source/UnrealEnginePython/Private/UnrealEnginePython.cpp

Python forcibly sets the file mode for stdin, stdout, and stderr to O_BINARY
for several reasons. This causes wprintf() to output UTF-16 instead of going
through the proper text conversion. As a result, standard output was all
messed up after the module was initialised.
The Python developers do not really consider this a bug because they are not
familiar with wprintf() (https://bugs.python.org/issue16587). Unfortunately
this is what UE4 uses for logging.

Restore Windows stdio flags after Python initialisation.

---

Source/UnrealEnginePython/Private/UEPyModule.cpp
Source/UnrealEnginePython/Private/Wrappers/UEPyFVector2D.cpp
Source/UnrealEnginePython/Private/Wrappers/UEPyFVector2D.h

This is a more obscure struct but I needed it so I figured I'd submit a patch for it too, based on the existing code for FVector.

added FVector2D wrapper

---

.gitignore
Source/PythonAutomation/Public/PythonAutomationModule.h
Source/UnrealEnginePython/Private/PythonHouseKeeper.cpp

Fix compilation errors and warnings for UE4.22.

Updates for UE4.22.

---

Source/UnrealEnginePython/Private/UEPyEditor.cpp
Source/UnrealEnginePython/Private/UEPyEditor.h
Source/UnrealEnginePython/Private/UEPyModule.cpp

Add support for removing components from blueprints to compliment
existing add component functionality

Add remove_component_from_blueprint
